### ISSUE TITLE
purpose of the program

### ISSUE THREAD

**Issue by muralikodali** [wojciechkepka/wutag#20]
Can we perform any file operations like copy,remove etc on the files based on tags ?
If not, is it intended for viewing tags only ?

is there a way to pipe file names only to stdout , to perform file operations ?

I request you to provide that feature ( just printing file names only) to make the program more useful.

**Comment by wojciechkepka** [comment]
Thanks for your feedback!

For now you cant perform any operations directly through wutag but you can surely use the search sub command to search for files that contain certain tags and use the `—raw` flag to make the output pipeable to other command.

I will have to think more on how to expand the functionality as for now it’s not very useful other than tagging and searching for files that are tagged.

If you have any other suggestions than please do share :) thanks.

**Comment by muralikodali** [comment]
using -raw flag giving following error

```
./wutag  -raw -d ~/Downloads/epubs search amazon                                                                                                                                                                                                                          20:45
error: Found argument '-a' which wasn't expected, or isn't valid in this context

If you tried to supply `-a` as a PATTERN use `-- -a`

USAGE:
    wutag [FLAGS] [OPTIONS] <SUBCOMMAND>

For more information try --help
```

**Comment by wojciechkepka** [comment]
The `--raw` flag should be prefixed with two `-` dashes. If you type `./wutag search --help` it will show you how to achieve what you need.

```
❯ wutag search --help
wutag-search
Searches for files that have all of the provided `tags`

USAGE:
    wutag search [FLAGS] <tags>...

ARGS:
    <tags>...

FLAGS:
    -h, --help       Prints help information
        --raw        If provided output will be raw so that it can be easily piped to other commands
```

**Comment by wojciechkepka** [comment]
So for example if you tag some files with `wutag set '*' photos` you can later do something like this:
`ls -l $(wutag search --raw photos)`

**Comment by muralikodali** [comment]
thanks for your suggestion.

now we can apply xargs or other command line utilities to process the output, which is very useful.
